name: Build the Python Application
on:
  workflow_dispatch:
    inputs:
      containerized:
        description: "Build a container version of the application"
        required: false
        type: boolean
        default: false
      publish:
        description: "Publish the package to PyPI"
        required: false
        type: boolean
        default: false
      python-version:
        description: "Python version to use"
        required: false
        type: choice
        options:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        default: "3.13"
      run-tests:
        description: "Run tests before building the package"
        required: false
        type: boolean
        default: true

jobs:
  build-package:
    name: Build the Python Package
    runs-on: ubuntu-latest
    timeout-minutes: 360
    if: ${{ false }}
    permissions:
      contents: read
    steps:
      ## Set an Initial Step
      - name: Workshop Initial Step
        run: |
          echo "Hello World!"

  ## NOTE: This section is for the second part of the Demo
  # build-container:
  #   name: Build the Python Container
  #   if: ${{ inputs.containerized }}
  #   uses: ./.github/workflows/build-container.yaml
  #   secrets:
  #     DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  #   with:
  #     publish: true
  #     python-version: ${{ inputs.python-version }}
